=== jackalkahwati/astroshield-infrastructure/src/welders_arc_schemas/schemas/ss0/launch-prediction/launch-window/0.1.0.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/launchWindow",
    "definitions": {
        "launchWindow": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "processTime": {
                    "type": "string",
                    "format": "date-time"
                },
                "phenomenology": {
                    "type": "string"
                },
                "eventId": {
                    "type": "string"
                },
                "locationInfo": {
                    "$ref": "#/definitions/LocationInfo"
                },
                "timeFrame": {
                    "$ref": "#/definitions/TimeFrame"
                }
            },
            "required": [
                "eventId",
                "locationInfo",
                "phenomenology",
                "processTime",
                "timeFrame"
            ],
            "title": "launchWindow"
        },
        "LocationInfo": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "launchSite": {
                    "type": "string"
                },
                "latitude": {
                    "type": "integer"
                },
                "longitude": {
                    "type": "integer"
                }
            },
            "required": [
                "latitude",
                "launchSite",
                "longitude"
            ],
            "title": "LocationInfo"
        },
        "TimeFrame": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "launchWindowStart": {
                    "type": "string",
                    "format": "date-time"
                },
                "launchWindowEnd": {
                    "type": "string",
                    "format": "date-time"
                }
            },
            "required": [
                "launchWindowEnd",
                "launchWindowStart"
            ],
            "title": "TimeFrame"
        }
    }
}

=== jackalkahwati/astroshield-infrastructure/src/welders_arc_schemas/schemas/ss0/launch-prediction/launch-window/examples/0.1.0.json
{
    "processTime": "2024-12-11T06:00:00.000Z",
    "phenomenology": "social_media",
    "eventId": "123-098-OUY-POI",
    "locationInfo": {
        "launchSite": "redSpacePort",
        "latitude": 54,
        "longitude": -129
    },
    "timeFrame": {
        "launchWindowStart": "2024-12-11T06:00:00.000Z",
        "launchWindowEnd": "2024-12-12T06:00:00.000Z"
    }
}
