=== jackalkahwati/astroshield-infrastructure/src/welders_arc_schemas/schemas/ss0/sensor/heartbeat/0.1.0.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/HeartbeatStatus",
    "definitions": {
        "HeartbeatStatus": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "uuid": {
                    "type": "string"
                },
                "time": {
                    "type": "string",
                    "format": "date-time"
                },
                "idSensor": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "weather": {
                    "$ref": "#/definitions/Weather"
                },
                "mobileSensor": {
                    "$ref": "#/definitions/MobileSensor"
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "idSensor",
                "status",
                "time",
                "uuid"
            ],
            "title": "HeartbeatStatus"
        },
        "MobileSensor": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "tle": {
                    "type": "string"
                }
            },
            "required": [
            ],
            "title": "MobileSensor"
        },
        "Weather": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "sunlit": {
                    "type": "boolean"
                },
                "overcastRatio": {
                    "type": "number"
                }
            },
            "required": [
            ],
            "title": "Weather"
        }
    }
}

=== jackalkahwati/astroshield-infrastructure/src/welders_arc_schemas/schemas/ss0/sensor/heartbeat/examples/0.1.0.json
{
    "uuid": "asdf-qwer-123-456",
    "time": "2024-12-10T06:00:00.000Z",
    "idSensor": "My_UDL_idSensor_Num",
    "status": "online",
    "weather": {
        "sunlit": false,
        "overcastRatio": 0.1
    },
    "mobileSensor": {
        "tle": "1 NNNNNU NNNNNAAA NNNNN.NNNNNNNN +.NNNNNNNN +NNNNN-N +NNNNN-N N NNNNN\n2 NNNNN NNN.NNNN NNN.NNNN NNNNNNN NNN.NNNN NNN.NNNN NN.NNNNNNNNNNNNNN"
    },
    "description": "Sensor Heartbeat Example!"
}
